baseURL: "https://roundtableofskillissue.github.io/blog/"
languageCode: en-us
title: RToSI
theme: PaperMod

menu:
  main:
    - identifier: sharing
      name: Sharing
      url: /sharing/
      weight: 10
    - identifier: writeups
      name: Writeups
      url: /writeup/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: member
      name: Members
      url: /member/
      weight: 40

params:
  profileMode:
        enabled: true
        title: "The Round Table of Skill Issue" # optional default will be site title
        subtitle: "Chả biết viết cái gì vô đây nữa..."
        imageUrl: "./home/image.png" # optional
        imageTitle: "teri teri" # optional
        imageWidth: 240 # custom size
        imageHeight: 200 # custom size
        buttons:
            - name: Đây là một chiếc nút vô dụng
              url: "./home/"
  socialIcons: # optional
        - name: "github"
          url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        - name: "email"
          url: "https://www.youtube.com/watch?v=fC7oUOUEEi4"

taxonomies:
  tag: tags
  author: members